name: greeny_solution_technician
description: "greeny_solution_technician"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  cupertino_icons: ^1.0.6
  
  shared:
    path: shared
  core:
    path: core
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  circular_menu : ^4.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  fab_circular_menu: ^1.0.2
  syncfusion_flutter_gauges: ^26.2.11
  curved_navigation_bar: ^1.0.6
  liquid_progress_indicator_v2: ^0.5.0
  camera: ^0.10.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  flutter_osm_plugin: ^1.3.3
  
  
  image_picker: ^0.8.9
 
  mobile_scanner: ^5.2.3
  geolocator: ^13.0.1
  
  pointer_interceptor: ^0.10.1+2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/greenycolor.png"  
flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/model/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: deseasedection3
      fonts:
        - asset: assets/fonts/deseasedection3.ttf
    - family: deseasedection1
      fonts:
        - asset: assets/fonts/deseasedetection1.ttf
